"""
FOIA Automation Service - Automated Freedom of Information Act request generation and tracking
"""
import os
import logging
from datetime import datetime, timezone, timedelta
from typing import Optional, List, Dict
import uuid

from app.db.database import db

logger = logging.getLogger(__name__)

# FOIA response deadlines by state (in days)
STATE_DEADLINES = {
    "federal": 20,
    "CA": 10,
    "NY": 5,
    "TX": 10,
    "FL": 30,
    "IL": 5,
    "default": 30
}

# Police department database (sample - in production, this would be a comprehensive database)
DEPARTMENT_DATABASE = {
    "LAPD": {
        "name": "Los Angeles Police Department",
        "state": "CA",
        "foia_email": "foia@lapd.online",
        "foia_address": "100 W 1st St, Los Angeles, CA 90012",
        "foia_portal": "https://lapdonline.org/foia",
        "body_cam_policy": "90 day retention",
        "avg_response_days": 15
    },
    "NYPD": {
        "name": "New York Police Department",
        "state": "NY",
        "foia_email": "foil@nypd.org",
        "foia_address": "1 Police Plaza, New York, NY 10038",
        "foia_portal": "https://www1.nyc.gov/nypd/foil",
        "body_cam_policy": "18 month retention",
        "avg_response_days": 20
    },
    "CPD": {
        "name": "Chicago Police Department",
        "state": "IL",
        "foia_email": "foia@chicagopolice.org",
        "foia_address": "3510 S Michigan Ave, Chicago, IL 60653",
        "foia_portal": "https://home.chicagopolice.org/foia",
        "body_cam_policy": "90 day retention",
        "avg_response_days": 30
    }
}


FOIA_REQUEST_TEMPLATE = """FREEDOM OF INFORMATION ACT REQUEST

Date: {date}
Reference Number: {reference_number}

To: {department_name}
    FOIA/Public Records Officer
    {department_address}

From: {requestor_name}
      {requestor_address}
      {requestor_email}

RE: Request for Police Records - Incident Date {incident_date}

Dear FOIA Officer,

Pursuant to the Freedom of Information Act (5 U.S.C. § 552) and applicable state public records laws, I am requesting copies of the following records:

1. BODY-WORN CAMERA FOOTAGE
   - All body-worn camera footage from officers involved in the incident
   - Date: {incident_date}
   - Time: {incident_time}
   - Location: {incident_location}
   - Officers involved: {officers_involved}

2. DASHCAM/VEHICLE CAMERA FOOTAGE
   - All dashboard and vehicle-mounted camera footage from the incident

3. INCIDENT REPORTS
   - All police reports, supplemental reports, and field contact cards
   - Computer-aided dispatch (CAD) records
   - Radio communications logs

4. OFFICER INFORMATION
   - Badge numbers and names of all officers present
   - Use of force reports (if applicable)
   - Officer disciplinary records related to similar incidents

DESCRIPTION OF INCIDENT:
{incident_description}

I am willing to pay reasonable fees for the processing of this request up to ${max_fee}. Please notify me before processing if fees will exceed this amount.

If any portion of this request is denied, please cite the specific exemption and provide a detailed explanation for each withheld document.

As this request involves potential civil rights concerns, I request expedited processing pursuant to applicable regulations.

Please respond within the time frame required by law ({deadline_days} working days).

Thank you for your prompt attention to this matter.

Sincerely,

{requestor_name}
{requestor_phone}
{requestor_email}

---
Request generated by JUSTICE Platform
Reference: {reference_number}
"""


async def generate_foia_request(
    user_id: str,
    encounter_id: str,
    department_code: Optional[str] = None,
    custom_department: Optional[Dict] = None
) -> Dict:
    """
    Generate a complete FOIA request for body cam footage and related records.
    """
    request_id = f"foia_{uuid.uuid4().hex[:12]}"
    
    # Get user info
    user = await db.users.find_one(
        {"user_id": user_id},
        {"_id": 0, "name": 1, "email": 1, "phone": 1, "address": 1}
    )
    
    if not user:
        return {"error": "User not found"}
    
    # Get encounter info
    encounter = await db.encounters.find_one(
        {"encounter_id": encounter_id},
        {"_id": 0}
    )
    
    if not encounter:
        return {"error": "Encounter not found"}
    
    # Get department info
    if department_code and department_code in DEPARTMENT_DATABASE:
        department = DEPARTMENT_DATABASE[department_code]
    elif custom_department:
        department = custom_department
    else:
        department = {
            "name": encounter.get("department_name", "Police Department"),
            "state": "default",
            "foia_email": "",
            "foia_address": "Address not specified",
            "body_cam_policy": "Unknown"
        }
    
    # Calculate deadline
    state = department.get("state", "default")
    deadline_days = STATE_DEADLINES.get(state, STATE_DEADLINES["default"])
    
    # Format the request
    incident_date = encounter.get("started_at")
    if isinstance(incident_date, datetime):
        incident_date_str = incident_date.strftime("%B %d, %Y")
        incident_time_str = incident_date.strftime("%I:%M %p")
    else:
        incident_date_str = str(incident_date)
        incident_time_str = "Time not recorded"
    
    location = encounter.get("location", {})
    location_str = f"{location.get('address', 'Address not recorded')}"
    if location.get("lat") and location.get("lng"):
        location_str += f" (GPS: {location['lat']}, {location['lng']})"
    
    officers = encounter.get("officer_info", {})
    officers_str = officers.get("badge_number", "Unknown") if officers else "Unknown - to be identified"
    
    request_text = FOIA_REQUEST_TEMPLATE.format(
        date=datetime.now(timezone.utc).strftime("%B %d, %Y"),
        reference_number=request_id,
        department_name=department.get("name"),
        department_address=department.get("foia_address"),
        requestor_name=user.get("name", "Name"),
        requestor_address=user.get("address", "Address"),
        requestor_email=user.get("email", "Email"),
        requestor_phone=user.get("phone", "Phone"),
        incident_date=incident_date_str,
        incident_time=incident_time_str,
        incident_location=location_str,
        officers_involved=officers_str,
        incident_description=encounter.get("description", "Police encounter - details in attached records"),
        max_fee="50.00",
        deadline_days=deadline_days
    )
    
    # Calculate tracking dates
    submitted_date = datetime.now(timezone.utc)
    response_due = submitted_date + timedelta(days=deadline_days)
    escalation_date = response_due + timedelta(days=7)
    
    # Create the request record
    foia_request = {
        "request_id": request_id,
        "user_id": user_id,
        "encounter_id": encounter_id,
        "department": department,
        "request_text": request_text,
        "status": "draft",
        "submitted_date": None,
        "response_due": response_due,
        "escalation_date": escalation_date,
        "deadline_days": deadline_days,
        "created_at": datetime.now(timezone.utc),
        "tracking": {
            "reminders_sent": 0,
            "last_reminder": None,
            "responses": []
        }
    }
    
    await db.foia_requests.insert_one(foia_request)
    
    # Return without _id
    foia_request.pop("_id", None)
    
    return {
        "request_id": request_id,
        "request_text": request_text,
        "department": department,
        "deadline_days": deadline_days,
        "response_due": response_due.isoformat(),
        "submit_to": {
            "email": department.get("foia_email"),
            "address": department.get("foia_address"),
            "portal": department.get("foia_portal")
        }
    }


async def submit_foia_request(request_id: str, submission_method: str = "email") -> Dict:
    """Mark a FOIA request as submitted and start tracking"""
    
    submitted_date = datetime.now(timezone.utc)
    
    result = await db.foia_requests.update_one(
        {"request_id": request_id},
        {
            "$set": {
                "status": "submitted",
                "submitted_date": submitted_date,
                "submission_method": submission_method
            }
        }
    )
    
    if result.modified_count == 0:
        return {"error": "Request not found"}
    
    # Schedule reminders
    # TODO: Integrate with scheduler to send reminders
    
    return {
        "success": True,
        "submitted_date": submitted_date.isoformat(),
        "message": f"Request marked as submitted via {submission_method}"
    }


async def update_foia_status(
    request_id: str,
    new_status: str,
    response_notes: Optional[str] = None,
    documents_received: Optional[List[str]] = None
) -> Dict:
    """Update the status of a FOIA request"""
    
    valid_statuses = ["draft", "submitted", "acknowledged", "processing", 
                      "partial_response", "completed", "denied", "appealed", "escalated"]
    
    if new_status not in valid_statuses:
        return {"error": f"Invalid status. Must be one of: {valid_statuses}"}
    
    update = {
        "status": new_status,
        "updated_at": datetime.now(timezone.utc)
    }
    
    if response_notes:
        update["$push"] = {
            "tracking.responses": {
                "date": datetime.now(timezone.utc),
                "notes": response_notes,
                "status": new_status
            }
        }
    
    if documents_received:
        update["documents_received"] = documents_received
    
    await db.foia_requests.update_one(
        {"request_id": request_id},
        {"$set": update}
    )
    
    return {"success": True, "new_status": new_status}


async def get_user_foia_requests(user_id: str) -> List[Dict]:
    """Get all FOIA requests for a user"""
    
    requests = await db.foia_requests.find(
        {"user_id": user_id},
        {"_id": 0}
    ).sort("created_at", -1).to_list(100)
    
    # Add status indicators
    now = datetime.now(timezone.utc)
    for req in requests:
        response_due = req.get("response_due")
        if response_due and isinstance(response_due, datetime):
            days_until_due = (response_due - now).days
            req["days_until_due"] = days_until_due
            req["overdue"] = days_until_due < 0
    
    return requests


async def generate_appeal_letter(request_id: str, denial_reason: str) -> Dict:
    """Generate an appeal letter for a denied FOIA request"""
    
    request = await db.foia_requests.find_one(
        {"request_id": request_id},
        {"_id": 0}
    )
    
    if not request:
        return {"error": "Request not found"}
    
    appeal_template = f"""FOIA APPEAL

Date: {datetime.now(timezone.utc).strftime("%B %d, %Y")}
Original Request Reference: {request_id}

To: {request.get('department', {}).get('name', 'Police Department')}
    FOIA Appeals Officer

RE: Appeal of Denial - Original Request dated {request.get('created_at', 'Unknown')}

Dear Appeals Officer,

I am writing to appeal the denial of my Freedom of Information Act request referenced above.

REASON FOR DENIAL PROVIDED:
{denial_reason}

GROUNDS FOR APPEAL:
1. The requested records are matters of public interest concerning police conduct.
2. The exemption cited does not apply to the specific records requested.
3. Any personal information can be redacted while still providing the substantive records.
4. The public interest in disclosure outweighs any privacy concerns.

I request that you review this denial and release the requested records.

If this appeal is denied, please provide detailed justification citing specific exemptions and explaining why no segregable portions can be released.

Sincerely,
[Requestor Name]

---
Appeal generated by JUSTICE Platform
"""
    
    return {
        "appeal_text": appeal_template,
        "original_request_id": request_id,
        "instructions": "Review and personalize this appeal letter before submitting to the appeals officer."
    }


async def get_foia_statistics() -> Dict:
    """Get overall FOIA request statistics"""
    
    pipeline = [
        {
            "$group": {
                "_id": "$status",
                "count": {"$sum": 1}
            }
        }
    ]
    
    status_counts = await db.foia_requests.aggregate(pipeline).to_list(20)
    
    total = await db.foia_requests.count_documents({})
    completed = await db.foia_requests.count_documents({"status": "completed"})
    denied = await db.foia_requests.count_documents({"status": "denied"})
    
    return {
        "total_requests": total,
        "by_status": {item["_id"]: item["count"] for item in status_counts},
        "success_rate": (completed / total * 100) if total > 0 else 0,
        "denial_rate": (denied / total * 100) if total > 0 else 0
    }
