"""
Templated PDF Generator - Creates PDFs using custom report templates
"""
import logging
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
from fpdf import FPDF

logger = logging.getLogger(__name__)


def hex_to_rgb(hex_color: str) -> tuple:
    """Convert hex color to RGB tuple"""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) != 6:
        return (79, 70, 229)  # Default indigo
    try:
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    except ValueError:
        return (79, 70, 229)


def get_section_key(section_name: str) -> str:
    """Map section name to config key"""
    section_map = {
        'OVERVIEW': 'show_overview',
        'KEY': 'show_key_points',
        'DISCUSSION': 'show_key_points',
        'ACTION': 'show_action_items',
        'LEGAL': 'show_legal_concerns',
        'CONCERN': 'show_legal_concerns',
        'RECOMMEND': 'show_recommendations',
        'FOLLOW': 'show_follow_up',
    }
    upper_name = section_name.upper()
    for key, config_key in section_map.items():
        if key in upper_name:
            return config_key
    return None


class TemplatedPDF(FPDF):
    """PDF class that uses template settings"""
    
    def __init__(self, template: dict = None):
        super().__init__()
        self.template = template or {}
        self.branding = self.template.get('branding', {})
        self.sections = self.template.get('sections', {})
        
        # Extract colors
        self.primary_color = hex_to_rgb(self.branding.get('primary_color', '#4f46e5'))
        self.secondary_color = hex_to_rgb(self.branding.get('secondary_color', '#7c3aed'))
        self.accent_color = hex_to_rgb(self.branding.get('accent_color', '#3b82f6'))
        
        # Extract text
        self.firm_name = self.branding.get('firm_name') or 'JUSTICE Platform'
        self.header_text = self.template.get('header_text')
        self.footer_text = self.template.get('footer_text')
        self.intro_message = self.template.get('intro_message')
        self.confidentiality_notice = self.template.get('confidentiality_notice') or (
            "This document contains confidential attorney-client communication. "
            "If you are not the intended recipient, please delete this document."
        )
    
    def header(self):
        # Firm name / header
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(*self.primary_color)
        self.cell(0, 10, self.firm_name.upper(), 0, 1, 'C')
        
        # Subtitle
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(0)
        title = self.header_text or 'Call Consultation Summary'
        self.cell(0, 8, title, 0, 1, 'C')
        
        # Tagline
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(128)
        self.cell(0, 5, 'AI-Generated Legal Consultation Summary', 0, 1, 'C')
        self.set_text_color(0)
        
        # Line with primary color
        self.set_draw_color(*self.primary_color)
        self.line(10, 35, 200, 35)
        self.ln(10)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        footer = self.footer_text or f'Generated by {self.firm_name}'
        self.cell(0, 10, f'Page {self.page_no()} | {footer} | {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}', 0, 0, 'C')
        self.set_text_color(0)
    
    def should_show_section(self, section_name: str) -> bool:
        """Check if a section should be shown based on template config"""
        config_key = get_section_key(section_name)
        if config_key is None:
            return True  # Show unknown sections by default
        return self.sections.get(config_key, True)
    
    def get_section_color(self, section_name: str) -> tuple:
        """Get color for a section header"""
        upper_name = section_name.upper()
        
        # Use template colors based on section type
        if 'ACTION' in upper_name:
            return (34, 197, 94)  # Green for actions
        elif 'LEGAL' in upper_name or 'CONCERN' in upper_name:
            return (239, 68, 68)  # Red for legal concerns
        elif 'RECOMMEND' in upper_name:
            return (245, 158, 11)  # Amber for recommendations
        elif 'KEY' in upper_name or 'DISCUSSION' in upper_name:
            return self.accent_color
        elif 'FOLLOW' in upper_name:
            return (107, 114, 128)  # Gray for follow-up
        
        return self.secondary_color  # Default to secondary color


def generate_single_summary_pdf(
    recording: dict,
    call: dict,
    summary: str,
    template: dict = None
) -> bytes:
    """Generate a PDF for a single recording with optional template"""
    
    pdf = TemplatedPDF(template)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    
    sections_config = template.get('sections', {}) if template else {}
    
    # Get recording info
    caller_name = call.get("caller_name", "Unknown") if call else "Unknown"
    recipient_name = call.get("recipient_name", "Unknown") if call else "Unknown"
    duration_seconds = recording.get("duration_seconds", 0)
    started_at = recording.get("started_at")
    summarized_at = recording.get("summarized_at")
    recording_id = recording.get("recording_id", "N/A")
    
    # Format dates
    if started_at and hasattr(started_at, 'strftime'):
        started_at_str = started_at.strftime('%B %d, %Y at %I:%M %p')
    else:
        started_at_str = str(started_at) if started_at else "Unknown"
    
    if summarized_at and hasattr(summarized_at, 'strftime'):
        summarized_at_str = summarized_at.strftime('%B %d, %Y at %I:%M %p')
    else:
        summarized_at_str = str(summarized_at) if summarized_at else "Unknown"
    
    duration_str = f"{duration_seconds // 60}m {duration_seconds % 60}s" if duration_seconds else "N/A"
    
    # Intro message if exists
    if pdf.intro_message:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(80)
        pdf.multi_cell(0, 5, pdf.intro_message)
        pdf.set_text_color(0)
        pdf.ln(5)
    
    # Call Information Section (if enabled)
    if sections_config.get('show_call_info', True):
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_fill_color(*pdf.primary_color)
        pdf.set_text_color(255)
        pdf.cell(0, 8, '  CALL INFORMATION', 0, 1, 'L', fill=True)
        pdf.set_text_color(0)
        pdf.ln(3)
        
        info_items = [
            ('Recording ID:', recording_id),
            ('Participants:', f'{caller_name} and {recipient_name}'),
            ('Call Date:', started_at_str),
            ('Duration:', duration_str),
            ('Summary Generated:', summarized_at_str),
        ]
        
        for label, value in info_items:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(50, 6, label, 0, 0)
            pdf.set_font('Helvetica', '', 10)
            value_str = str(value)[:80] if len(str(value)) > 80 else str(value)
            pdf.cell(0, 6, value_str, 0, 1)
        
        pdf.ln(5)
    
    # Parse and render summary sections
    current_section = None
    skip_until_next_section = False
    
    lines = summary.split('\n')
    for line in lines:
        # Check for page break
        if pdf.get_y() > 260:
            pdf.add_page()
        
        clean_line = line.strip()
        
        # Skip empty lines but add small space
        if not clean_line:
            if not skip_until_next_section:
                pdf.ln(2)
            continue
        
        # Section headers (numbered like "1. **OVERVIEW**" or "**OVERVIEW**")
        is_section_header = False
        section_text = clean_line
        
        if clean_line.startswith('**') and clean_line.endswith('**'):
            is_section_header = True
            section_text = clean_line.replace('**', '')
        elif '**' in clean_line and clean_line[0].isdigit():
            parts = clean_line.split('**')
            if len(parts) >= 2:
                is_section_header = True
                section_text = parts[1] if parts[1] else (parts[2] if len(parts) > 2 else clean_line)
        
        if is_section_header:
            # Check if this section should be shown
            if not pdf.should_show_section(section_text):
                skip_until_next_section = True
                current_section = section_text
                continue
            else:
                skip_until_next_section = False
                current_section = section_text
            
            pdf.ln(3)
            color = pdf.get_section_color(section_text)
            pdf.set_fill_color(*color)
            pdf.set_text_color(255)
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(0, 7, f'  {section_text.upper()}', 0, 1, 'L', fill=True)
            pdf.set_text_color(0)
            pdf.ln(2)
            continue
        
        # Skip content if section is hidden
        if skip_until_next_section:
            continue
        
        # Bullet points
        if clean_line.startswith('-') or clean_line.startswith('•'):
            content = clean_line[1:].strip().replace('**', '')
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(5, 5, '', 0, 0)
            pdf.cell(5, 5, chr(149), 0, 0)  # Bullet character
            if len(content) > 90:
                pdf.set_x(20)
                pdf.multi_cell(0, 5, content)
            else:
                pdf.cell(0, 5, content, 0, 1)
            continue
        
        # Sub-bullet points (indented)
        if clean_line.startswith('  -') or clean_line.startswith('  •'):
            content = clean_line.strip()[1:].strip().replace('**', '')
            pdf.set_font('Helvetica', '', 9)
            pdf.cell(15, 5, '', 0, 0)
            pdf.cell(5, 5, '-', 0, 0)
            if len(content) > 80:
                pdf.set_x(30)
                pdf.multi_cell(0, 5, content)
            else:
                pdf.cell(0, 5, content, 0, 1)
            continue
        
        # Regular paragraph text
        content = clean_line.replace('**', '')
        pdf.set_font('Helvetica', '', 10)
        pdf.multi_cell(0, 5, content)
    
    # Confidentiality Notice
    pdf.ln(10)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 7, '  CONFIDENTIALITY NOTICE', 0, 1, 'L', fill=True)
    pdf.ln(2)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 5, pdf.confidentiality_notice)
    pdf.set_text_color(0)
    
    return bytes(pdf.output())


def generate_batch_summary_pdf(
    recordings_data: List[Dict[str, Any]],
    template: dict = None,
    user_name: str = "JUSTICE User"
) -> bytes:
    """Generate a consolidated PDF for multiple recordings with optional template"""
    
    pdf = TemplatedPDF(template)
    pdf.set_auto_page_break(auto=True, margin=20)
    
    sections_config = template.get('sections', {}) if template else {}
    
    # Table of Contents page
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_fill_color(*pdf.primary_color)
    pdf.set_text_color(255)
    pdf.cell(0, 10, '  TABLE OF CONTENTS', 0, 1, 'L', fill=True)
    pdf.set_text_color(0)
    pdf.ln(5)
    
    for idx, data in enumerate(recordings_data, 1):
        recording = data["recording"]
        call = data["call"]
        
        caller_name = call.get("caller_name", "Unknown") if call else "Unknown"
        recipient_name = call.get("recipient_name", "Unknown") if call else "Unknown"
        started_at = recording.get("started_at")
        
        if started_at and hasattr(started_at, 'strftime'):
            date_str = started_at.strftime('%b %d, %Y')
        else:
            date_str = str(started_at)[:10] if started_at else "Unknown"
        
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(10, 7, f'{idx}.', 0, 0)
        pdf.set_font('Helvetica', '', 11)
        pdf.cell(0, 7, f'{caller_name} & {recipient_name} - {date_str}', 0, 1)
    
    # Intro message if exists
    if pdf.intro_message:
        pdf.ln(10)
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(80)
        pdf.multi_cell(0, 5, pdf.intro_message)
        pdf.set_text_color(0)
    
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 5, 
        f'This consolidated report contains AI-generated summaries of {len(recordings_data)} '
        'attorney-client consultations. Each summary includes key discussion points, action items, '
        'and legal considerations. Original recordings remain the authoritative sources.'
    )
    pdf.set_text_color(0)
    
    # Individual summaries
    for idx, data in enumerate(recordings_data, 1):
        pdf.add_page()
        
        recording = data["recording"]
        call = data["call"]
        summary = data["summary"]
        
        caller_name = call.get("caller_name", "Unknown") if call else "Unknown"
        recipient_name = call.get("recipient_name", "Unknown") if call else "Unknown"
        duration_seconds = recording.get("duration_seconds", 0)
        started_at = recording.get("started_at")
        recording_id = recording.get("recording_id", "N/A")
        
        if started_at and hasattr(started_at, 'strftime'):
            started_at_str = started_at.strftime('%B %d, %Y at %I:%M %p')
        else:
            started_at_str = str(started_at) if started_at else "Unknown"
        
        duration_str = f"{duration_seconds // 60}m {duration_seconds % 60}s" if duration_seconds else "N/A"
        
        # Call header
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_fill_color(*pdf.accent_color)
        pdf.set_text_color(255)
        pdf.cell(0, 8, f'  CONSULTATION #{idx}: {caller_name} & {recipient_name}', 0, 1, 'L', fill=True)
        pdf.set_text_color(0)
        pdf.ln(3)
        
        # Call info (if enabled)
        if sections_config.get('show_call_info', True):
            info_items = [
                ('Recording ID:', recording_id),
                ('Date:', started_at_str),
                ('Duration:', duration_str),
            ]
            
            for label, value in info_items:
                pdf.set_font('Helvetica', 'B', 9)
                pdf.cell(35, 5, label, 0, 0)
                pdf.set_font('Helvetica', '', 9)
                pdf.cell(0, 5, str(value)[:60], 0, 1)
            
            pdf.ln(3)
        
        # Parse and render summary
        skip_until_next_section = False
        
        for line in summary.split('\n'):
            if pdf.get_y() > 260:
                pdf.add_page()
            
            clean_line = line.strip()
            
            if not clean_line:
                if not skip_until_next_section:
                    pdf.ln(2)
                continue
            
            # Section headers
            is_section_header = False
            section_text = clean_line
            
            if clean_line.startswith('**') and clean_line.endswith('**'):
                is_section_header = True
                section_text = clean_line.replace('**', '')
            elif '**' in clean_line and clean_line[0].isdigit():
                parts = clean_line.split('**')
                if len(parts) >= 2:
                    is_section_header = True
                    section_text = parts[1] if parts[1] else (parts[2] if len(parts) > 2 else clean_line)
            
            if is_section_header:
                if not pdf.should_show_section(section_text):
                    skip_until_next_section = True
                    continue
                else:
                    skip_until_next_section = False
                
                pdf.ln(2)
                color = pdf.get_section_color(section_text)
                pdf.set_fill_color(*color)
                pdf.set_text_color(255)
                pdf.set_font('Helvetica', 'B', 10)
                pdf.cell(0, 6, f'  {section_text.upper()}', 0, 1, 'L', fill=True)
                pdf.set_text_color(0)
                pdf.ln(1)
                continue
            
            if skip_until_next_section:
                continue
            
            # Bullet points
            if clean_line.startswith('-') or clean_line.startswith('•'):
                content = clean_line[1:].strip().replace('**', '')
                pdf.set_font('Helvetica', '', 9)
                pdf.cell(5, 4, '', 0, 0)
                pdf.cell(5, 4, chr(149), 0, 0)
                if len(content) > 90:
                    pdf.set_x(20)
                    pdf.multi_cell(0, 4, content)
                else:
                    pdf.cell(0, 4, content, 0, 1)
                continue
            
            # Sub-bullet points
            if clean_line.startswith('  -') or clean_line.startswith('  •'):
                content = clean_line.strip()[1:].strip().replace('**', '')
                pdf.set_font('Helvetica', '', 8)
                pdf.cell(15, 4, '', 0, 0)
                pdf.cell(5, 4, '-', 0, 0)
                if len(content) > 80:
                    pdf.set_x(30)
                    pdf.multi_cell(0, 4, content)
                else:
                    pdf.cell(0, 4, content, 0, 1)
                continue
            
            # Regular text
            content = clean_line.replace('**', '')
            pdf.set_font('Helvetica', '', 9)
            pdf.multi_cell(0, 4, content)
        
        pdf.ln(3)
    
    # Final page - disclaimer
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(100, 100, 100)
    pdf.set_text_color(255)
    pdf.cell(0, 8, '  CONFIDENTIALITY & DISCLAIMER', 0, 1, 'L', fill=True)
    pdf.set_text_color(0)
    pdf.ln(5)
    
    pdf.set_font('Helvetica', '', 10)
    disclaimers = [
        pdf.confidentiality_notice,
        "All summaries are AI-generated and should be reviewed by qualified legal counsel.",
        "Original recordings and transcripts remain the authoritative sources.",
        f"Report generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"Total consultations: {len(recordings_data)}",
    ]
    
    for disclaimer in disclaimers:
        pdf.cell(5, 6, chr(149), 0, 0)
        pdf.multi_cell(0, 6, disclaimer)
    
    return bytes(pdf.output())
